name: Test CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-24.04 ]

    steps:
      - uses: actions/checkout@v2
      - name: Update apt-get
        run: sudo apt-get update
      - name: Install packages
        run: sudo apt-get install -y --no-install-recommends python3
      - name: Install dependencies
        run: python -m pip install --upgrade pip
      - name: Run tests
        run: python3 -m unittest discover -s ./tests  -p 'test_*.py'