name: Test CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-24.04 ]

    steps:
      - uses: actions/checkout@v2
      - name: Update apt-get
        run: sudo apt-get update
      - name: Install packages
        run: sudo apt-get install -y --no-install-recommends python3 python3.12-venv
      - name: Create and source .venv
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pylint
      - name: Run linter
        run: pylint src tests
      - name: Run tests
        run: python3 -m unittest discover -s ./tests  -p 'test_*.py'